/*
 * This source file was generated by the Gradle 'init' task
 */
package estructurasdatos;

import java.sql.Date;

import estructurasdatos.Model.Auto.Automovil;
import estructurasdatos.Model.Auto.Camioneta;
import estructurasdatos.Model.Auto.Vehiculo;
import estructurasdatos.Model.Taller.Reparacion;
import estructurasdatos.Model.Service.FacturacionService;

public class App {
    

    public static void main(String[] args) {
        try {
            // Instanciar taller
            estructurasdatos.Model.Taller.Taller taller = new estructurasdatos.Model.Taller.Taller("Taller Central");

            // Instanciar vehículos
            Vehiculo camioneta1 = new Camioneta("Toyota", "Hilux", "Diesel", "ABC123");
            Vehiculo camioneta2 = new Camioneta("Ford", "Ranger", "Gasolina", "DEF456");
            Vehiculo automovil1 = new Automovil("Honda", "Civic", "Manual", "GHI789");
            Vehiculo automovil2 = new Automovil("Chevrolet", "Onix", "Automática", "JKL012");

            // Asignar reparaciones
            Reparacion rep1 = new Reparacion("Cambio de aceite", 250, new Date(System.currentTimeMillis()), "Aceite sintético");
            Reparacion rep2 = new Reparacion("Cambio de frenos", 400, new Date(System.currentTimeMillis()), "Pastillas de freno");
            Reparacion rep3 = new Reparacion("Reparación de motor", 1200, new Date(System.currentTimeMillis()), "Kit de motor");
            Reparacion rep4 = new Reparacion("Cambio de llantas", 800, new Date(System.currentTimeMillis()), "Llantas nuevas");
            Reparacion rep5 = new Reparacion("Alineación", 150, new Date(System.currentTimeMillis()), "Servicio");

            camioneta1.agregarReparacion(rep1);
            camioneta1.agregarReparacion(rep2);
            camioneta1.agregarReparacion(rep5);

            camioneta2.agregarReparacion(rep3);
            camioneta2.agregarReparacion(rep4);

            automovil1.agregarReparacion(rep2);
            automovil1.agregarReparacion(rep5);

            automovil2.agregarReparacion(rep1);
            automovil2.agregarReparacion(rep3);
            automovil2.agregarReparacion(rep4);

            // Agregar vehículos al taller
            taller.agregarVehiculo(camioneta1);
            taller.agregarVehiculo(camioneta2);
            taller.agregarVehiculo(automovil1);
            taller.agregarVehiculo(automovil2);

            // Generar facturación
            FacturacionService.generarFactura(camioneta1);
            FacturacionService.generarFactura(camioneta2);
            FacturacionService.generarFactura(automovil1);
            FacturacionService.generarFactura(automovil2);

            System.out.println("Facturación generada exitosamente para todos los vehículos.");
        } catch (Exception e) {
            System.out.println("Hubo error");
        }
    }
}
